spring:
  application:
    name: single-architecture-spring-boot-shopping-sample
  jpa:
    # enable or disable show data view in web console
    open-in-view: true
    # enable print sql
    show-sql: true
    hibernate:
      # create:Create the schema and destroy previous data
      # create-drop:Create and then destroy the schema at the end of the session.
      # update:Update the schema if necessary.
      # none:Disable DDL handling
      ddl-auto: none
      naming:
        # org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy:nickName mapping to NIKE_NAME
        # org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        # org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl extends ImplicitNamingStrategyJpaCompliantImpl
        # org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl extends ImplicitNamingStrategyJpaCompliantImpl
        # org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl extends ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: mysql
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://localhost:3306/spring_cloud_mysql8_test_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath*:schema.sql
    data: classpath*:data.sql
server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    sql: DEBUG
    web: INFO
    org:
      springframework: INFO
    com:
      xingyun:
        singlearchitecturespringbootshoppingsample: DEBUG


management:
  endpoint:
    health:
      show-details: when_authorized